export enum Modules{
    Dashboard = -1,
    MilestoneTracker = 1,
    DocumentManagement = 2,
    UserManagement = 3,
    DailyFieldReport = 4,
    ActivityManagement = 5,
    DriversManagement = 6,
    GcAssignment = 7,
    CrewForemanAssignment = 8,
    SampleDocumentsManagement = 9,
    ScopingTool = 10,
    Reports = 12,
    BudgetForecast = 13,
    BidCalculate = 14,
    DailyVehicleInspection = 15,
    Uform = 16,
    Workflow = 18,
    UserNotifications = 19,
    CrewPlanner = 20,
    PowerBi = 23,
    ProjectManagement = 21,
    WorkflowApplication = 22,
    DeliverableManagement = 24,
    VendorInvoice = 25,
    WorkOrder = 28,
    ScopingManagement = 27,
    POWorkflowApprovals = 29,
    ClientInvoice = 26,
    UserGuide = 30,
    CostCenterManagement = 31,
    WarehouseCheckIn = 37,
    ReceiveMaterials = 40,
    ChatEngine = 777
}

export enum SubModule {
    TowerService = 1,
    OrderFulfillment = 2,
    Closeouts = 3,
    POs = 4,
    ReceiveMaterials3PL = 6,
    ReceiveMaterialsNexius = 7,
    GroundServiceCivil = 8,
    GroundServicePowerPlant = 9,
    GroundServiceSmallCell = 10,
    GroundServiceIntegration = 11
}

